# Generated by Django 2.1.2 on 2018-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [['Can_view_gold_page', 'Can View Gold Page']]},
        ),
    ]
